#+OPTIONS: toc:nil  
#+OPTIONS: num:nil
#+TITLE: GNU Emacs snapshot packages

* Overview

This is an APT repository that provides unofficial snapshot Debian packages for
GNU Emacs. These are built from the latest commit in the GNU Emacs repository,
so they represent the bleeding edge of Emacs development. As such, these could
contain bugs.

*Packages are generated weekly by a script and not tested by anybody. Use at
your own risk.*

These packages are built for the =amd64= architecture. Debian/wheezy is
targeted, and things should work there and on Debian/sid.

* Instructions

Add to your =/etc/apt/sources.list=:

#+BEGIN_EXAMPLE
deb     [arch=amd64] http://emacs.secretsauce.net unstable main
deb-src [arch=amd64] http://emacs.secretsauce.net unstable main
#+END_EXAMPLE

To tell APT to trust these packages, do

#+BEGIN_EXAMPLE
wget -q -O - http://emacs.secretsauce.net/key.gpg | sudo apt-key add -
#+END_EXAMPLE

Packages are named =emacs-snapshot...=. Sources are available with =apt-get
source= as usual. 

* Bugs

As stated previously, these packages are unsupported. If you encounter an issue,
/do not/ report it to the Debian emacs maintainers. Try to reproduce your issue
with =emacs -Q= and with building emacs from source. If the issue is
reproducible then, you should report it directly to the GNU Emacs maintainers.

Of course, if there are any problems with the packaging and distribution itself,
don't hesitate to contact me.

* Provenance

These packages were maintained by a series of people. The latest was Julien
Danjou at http://emacs.naquadah.org/. The packaging data utilized here is mostly
taken from his repository.

The tree used to build these packages is at https://github.com/dkogan/emacs. The
=upstream= branch is the GNU Emacs source, and the =master= branch is the
debianization.

* Contact

The current maintainer is Dima Kogan <dima at secretsauce dot net>.
